import { Film } from "@/types";

export const sampleFilms: Omit<Film, '_id' | 'createdAt'>[] = [
    {
        title: 'Stranger Things',
        description: 'Set in the fictional town of Hawkins, Indiana, during the 1980s, the series follows a group of friends who uncover a government laboratory\'s secret experiments, a parallel dimension known as the Upside Down, and supernatural threats that emerge from it.',
        genre: ['Sci-Fi', 'Drama', 'Horror'],
        releaseYear: 2016,
        runningTime: 51, // average episode running time
        rating: 8.7,
        imageUrl: 'https://unsplash.com/es/fotos/senalizacion-de-stranger-things-07_BEPOHcKg?w=800&h=450&fit=crop',
        category: 'series',
        featured: true,
        trending: true,
    },
    {
        title: 'The Crown',
        description: 'The series spans almost six decades, beginning shortly before the wedding of Princess Elizabeth and Philip Mountbatten in 1947 and ending with the 2005 wedding of Prince Charles and Camilla Parker Bowles',
        genre: ['Drama', 'Biography', 'History'],
        releaseYear: 2016,
        runningTime: 58, // average episode running time
        rating: 8.7,
        imageUrl: 'https://unsplash.com/es/fotos/senalizacion-de-stranger-things-07_BEPOHcKg?w=800&h=450&fit=crop',
        category: 'series',
        featured: true,
        trending: true,
    },
    {
        title: 'Frankenstein',
        description: 'A new adaptation of Mary Shelley\'s classic directed by Guillermo Del Toro',
        genre: ['Drama', 'Horror', 'Sci-Fi'],
        releaseYear: 2025,
        runningTime: 149, 
        rating: 7.5,
        imageUrl: 'https://unsplash.com/es/fotos/senalizacion-de-stranger-things-07_BEPOHcKg?w=800&h=450&fit=crop',
        category: 'film',
        featured: true,
        trending: true,
    },
    {
        title: 'Beasts of no Nation',
        description: 'When civil war tears his family apart, a young West African boy is forced to join a unit of mercenary fighters.',
        genre: ['Drama', 'War'],
        releaseYear: 2015,
        runningTime: 137, 
        rating: 7.7,
        imageUrl: 'https://unsplash.com/es/fotos/senalizacion-de-stranger-things-07_BEPOHcKg?w=800&h=450&fit=crop',
        category: 'film',
        featured: true,
        trending: true,
    },
    {
        title: 'Carry-On',
        description: 'An airport security officer races to outsmart a mysterious traveler forcing him to let a dangerous item slip onto a Christmas Eve flight.',
        genre: ['ACtion', 'Thriller'],
        releaseYear: 2024,
        runningTime: 119, 
        rating: 7.7,
        imageUrl: 'https://unsplash.com/es/fotos/senalizacion-de-stranger-things-07_BEPOHcKg?w=800&h=450&fit=crop',
        category: 'film',
        featured: true,
        trending: true,
    },
];